"""备注

Revision ID: b4ba83f49739
Revises: bfeb97ce0dee
Create Date: 2020-01-01 00:15:19.684790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ba83f49739'
down_revision = 'bfeb97ce0dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'factory_order', 'driver_order', ['driver_order_uuid'], ['order_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factory_order', type_='foreignkey')
    # ### end Alembic commands ###
