"""备注

Revision ID: bfeb97ce0dee
Revises: 
Create Date: 2020-01-01 00:07:24.641425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfeb97ce0dee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自动编号'),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=False, comment='唯一编号'),
    sa.Column('open_id', sa.String(length=32), nullable=True, comment='用户微信uuid'),
    sa.Column('name', sa.String(length=10), nullable=True, comment='管理员姓名'),
    sa.Column('phone', sa.String(length=13), nullable=False, comment='手机号'),
    sa.Column('sms_status', sa.Boolean(), nullable=True, comment='是否接收短信的状态'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_id')
    )
    op.create_index(op.f('ix_admin_uuid'), 'admin', ['uuid'], unique=True)
    op.create_table('driver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自动编号'),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=False, comment='唯一编号'),
    sa.Column('open_id', sa.String(length=32), nullable=False, comment='用户微信uuid'),
    sa.Column('name', sa.String(length=10), nullable=False, comment='用户名:驾驶员名'),
    sa.Column('phone', sa.String(length=13), nullable=False, comment='手机号'),
    sa.Column('number_plate', sa.String(length=10), nullable=True, comment='车牌号:驾驶员特有字段'),
    sa.Column('verify', sa.SMALLINT(), nullable=True, comment='账号审核状态. -2:封禁 -1:审核失败 0:待审核 1:审核通过'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_id')
    )
    op.create_index(op.f('ix_driver_uuid'), 'driver', ['uuid'], unique=True)
    op.create_table('factory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自动编号'),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=False, comment='唯一编号'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='订单地址'),
    sa.Column('address_replenish', sa.String(length=255), nullable=True, comment='订单地址补充'),
    sa.Column('open_id', sa.String(length=32), nullable=False, comment='用户微信uuid'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='用户名:厂家名'),
    sa.Column('phone', sa.String(length=13), nullable=False, comment='手机号'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_id')
    )
    op.create_index(op.f('ix_factory_uuid'), 'factory', ['uuid'], unique=True)
    op.create_table('images',
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(length=32), nullable=False, comment='用户ID'),
    sa.Column('url', sa.String(length=255), nullable=False, comment='图片地址'),
    sa.Column('genre', sa.String(length=10), nullable=False, comment='图片用途'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('factory_contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自动编号'),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='订单地址'),
    sa.Column('address_replenish', sa.String(length=255), nullable=True, comment='订单地址补充'),
    sa.Column('contact_name', sa.String(length=20), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=13), nullable=False, comment='手机号'),
    sa.Column('factory_uuid', sa.String(length=40), nullable=False, comment='厂家UUID'),
    sa.ForeignKeyConstraint(['factory_uuid'], ['factory.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自动编号'),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('order_uuid', sa.String(length=12), nullable=False, comment='唯一编号'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='订单地址'),
    sa.Column('address_replenish', sa.String(length=255), nullable=True, comment='订单地址补充'),
    sa.Column('contact_name', sa.String(length=20), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=13), nullable=False, comment='手机号'),
    sa.Column('factory_uuid', sa.String(length=40), nullable=False, comment='厂家UUID'),
    sa.Column('description', sa.Text(), nullable=True, comment='订单详情'),
    sa.Column('images', sa.JSON(), nullable=True, comment='订单图片'),
    sa.Column('date', sa.Date(), nullable=True, comment='订单开始日期'),
    sa.Column('time', sa.Time(), nullable=True, comment='订单具体时间'),
    sa.Column('schedule', sa.SMALLINT(), nullable=True, comment='订单进度:0:待接单,1:已接单,2:已完成'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='订单内容更新时间'),
    sa.Column('driver_order_uuid', sa.String(length=12), nullable=True, comment='驾驶员订单编号'),
    sa.ForeignKeyConstraint(['factory_uuid'], ['factory.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_order_order_uuid'), 'factory_order', ['order_uuid'], unique=True)
    op.create_index(op.f('ix_factory_order_schedule'), 'factory_order', ['schedule'], unique=False)
    op.create_table('driver_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自动编号'),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('order_uuid', sa.String(length=12), nullable=False, comment='唯一编号'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='订单地址'),
    sa.Column('address_replenish', sa.String(length=255), nullable=True, comment='订单地址补充'),
    sa.Column('contact_name', sa.String(length=20), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=13), nullable=False, comment='手机号'),
    sa.Column('driver_uuid', sa.String(length=40), nullable=False, comment='驾驶员UUID'),
    sa.Column('factory_order_uuid', sa.String(length=12), nullable=True, comment='订单编号'),
    sa.Column('description', sa.Text(), nullable=True, comment='订单详情'),
    sa.Column('images', sa.JSON(), nullable=True, comment='订单图片'),
    sa.Column('date', sa.Date(), nullable=True, comment='订单开始日期'),
    sa.Column('time', sa.Time(), nullable=True, comment='订单具体时间'),
    sa.Column('driver_schedule', sa.SMALLINT(), nullable=True, comment='驾驶员进度:-1:订单已取消,0:未接单1:已接单,2:已出发,3:已到达厂家,4:返程中,5:已送达,6:已验收'),
    sa.ForeignKeyConstraint(['driver_uuid'], ['driver.uuid'], ),
    sa.ForeignKeyConstraint(['factory_order_uuid'], ['factory_order.order_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_order_order_uuid'), 'driver_order', ['order_uuid'], unique=True)
    op.create_table('driver_order_schedule_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自动编号'),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('driver_order_uuid', sa.String(length=12), nullable=True, comment='订单编号'),
    sa.Column('schedule', sa.SMALLINT(), nullable=True, comment='驾驶员进度:0:未接单1:已接单,2:已出发,3:已到达厂家,4:返程中,5:已送达,6:已验收,-1:订单已取消'),
    sa.ForeignKeyConstraint(['driver_order_uuid'], ['driver_order.order_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_order_schedule_log')
    op.drop_index(op.f('ix_driver_order_order_uuid'), table_name='driver_order')
    op.drop_table('driver_order')
    op.drop_index(op.f('ix_factory_order_schedule'), table_name='factory_order')
    op.drop_index(op.f('ix_factory_order_order_uuid'), table_name='factory_order')
    op.drop_table('factory_order')
    op.drop_table('factory_contact')
    op.drop_table('images')
    op.drop_index(op.f('ix_factory_uuid'), table_name='factory')
    op.drop_table('factory')
    op.drop_index(op.f('ix_driver_uuid'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_admin_uuid'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
